#!perl
use strict;
use warnings;
use IO::Interactive::Tiny;
use Encode qw//;

my $encoding = shift @ARGV;

unless ( IO::Interactive::Tiny::is_interactive(*STDIN) ) {
    my $dump_str = join '', <STDIN>;
    $dump_str =~ s/\\x\{([0-9a-f]+)\}/_unescape($1)/ge;
    print $dump_str;
}

sub _unescape {
    my ($code) = @_;

    Encode::encode($encoding || 'utf8', chr(hex $code));
}
